package test.professional.exceptions2;

import java.io.FileNotFoundException;

public class ExceptionThrowerOne {
    public void method() throws ArithmeticException, FileNotFoundException, Exception {}
}
